[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="recentTitles" type="java.lang.String[]" --]
[#-- @ftlvariable name="site" type="java.util.Hashtable<Object,Object>" --]
[#-- @ftlvariable name="timeCount" type="java.util.HashMap<String,MutableInt>" --]
[#-- @ftlvariable name="categoryCount" type="java.util.TreeMap<String,MutableInt>" --]
[#-- @ftlvariable name="view" type="org.reindeer.simpleblog.core.model.AbstractView" file="../webapp/WEB-INF/template/side.ftl"--]
[#-- @ftlvariable name="view" type="org.reindeer.simpleblog.core.model.PageView" file="../webapp/WEB-INF/template/home.ftl" --]
[#-- @ftlvariable name="view" type="org.reindeer.simpleblog.core.model.BlogView" file="../webapp/WEB-INF/template/blog.ftl"--]
